// Code generated by protoc-gen-go. DO NOT EDIT.
// source: anyvendor.proto

package anyvendor

import (
	fmt "fmt"
	math "math"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
//Config object used for running anyvendor. The top level config consists of 2 main sections.
//
//Local is a set of matchers will be taken directly from the local module, and vendored in.
//Imports is a list of import types which will be run, and then vendored.
type Config struct {
	Local                *Local    `protobuf:"bytes,1,opt,name=local,proto3" json:"local,omitempty"`
	Imports              []*Import `protobuf:"bytes,2,rep,name=imports,proto3" json:"imports,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a8ec572c73c9b71, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLocal() *Local {
	if m != nil {
		return m.Local
	}
	return nil
}

func (m *Config) GetImports() []*Import {
	if m != nil {
		return m.Imports
	}
	return nil
}

type Import struct {
	// Types that are valid to be assigned to ImportType:
	//	*Import_GoMod
	ImportType           isImport_ImportType `protobuf_oneof:"ImportType"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Import) Reset()         { *m = Import{} }
func (m *Import) String() string { return proto.CompactTextString(m) }
func (*Import) ProtoMessage()    {}
func (*Import) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a8ec572c73c9b71, []int{1}
}

func (m *Import) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Import.Unmarshal(m, b)
}
func (m *Import) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Import.Marshal(b, m, deterministic)
}
func (m *Import) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Import.Merge(m, src)
}
func (m *Import) XXX_Size() int {
	return xxx_messageInfo_Import.Size(m)
}
func (m *Import) XXX_DiscardUnknown() {
	xxx_messageInfo_Import.DiscardUnknown(m)
}

var xxx_messageInfo_Import proto.InternalMessageInfo

type isImport_ImportType interface {
	isImport_ImportType()
}

type Import_GoMod struct {
	GoMod *GoModImport `protobuf:"bytes,2,opt,name=go_mod,json=goMod,proto3,oneof"`
}

func (*Import_GoMod) isImport_ImportType() {}

func (m *Import) GetImportType() isImport_ImportType {
	if m != nil {
		return m.ImportType
	}
	return nil
}

func (m *Import) GetGoMod() *GoModImport {
	if x, ok := m.GetImportType().(*Import_GoMod); ok {
		return x.GoMod
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Import) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Import_GoMod)(nil),
	}
}

// A set of glob patters to be grabbed from the current module
type Local struct {
	Patterns             []string `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Local) Reset()         { *m = Local{} }
func (m *Local) String() string { return proto.CompactTextString(m) }
func (*Local) ProtoMessage()    {}
func (*Local) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a8ec572c73c9b71, []int{2}
}

func (m *Local) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Local.Unmarshal(m, b)
}
func (m *Local) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Local.Marshal(b, m, deterministic)
}
func (m *Local) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Local.Merge(m, src)
}
func (m *Local) XXX_Size() int {
	return xxx_messageInfo_Local.Size(m)
}
func (m *Local) XXX_DiscardUnknown() {
	xxx_messageInfo_Local.DiscardUnknown(m)
}

var xxx_messageInfo_Local proto.InternalMessageInfo

func (m *Local) GetPatterns() []string {
	if m != nil {
		return m.Patterns
	}
	return nil
}

//
//A go mod import represents a set of imports from a go module
//
//patterns is a set glob matchers to find files in a go module.
//
//package is the name of the go module which these should be pulled from.
//
//The GoModImport uses the command `go list -f '{{.Path}}' -m  all` to find
//all of the package names
type GoModImport struct {
	Patterns             []string `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Package              string   `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoModImport) Reset()         { *m = GoModImport{} }
func (m *GoModImport) String() string { return proto.CompactTextString(m) }
func (*GoModImport) ProtoMessage()    {}
func (*GoModImport) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a8ec572c73c9b71, []int{3}
}

func (m *GoModImport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoModImport.Unmarshal(m, b)
}
func (m *GoModImport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoModImport.Marshal(b, m, deterministic)
}
func (m *GoModImport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoModImport.Merge(m, src)
}
func (m *GoModImport) XXX_Size() int {
	return xxx_messageInfo_GoModImport.Size(m)
}
func (m *GoModImport) XXX_DiscardUnknown() {
	xxx_messageInfo_GoModImport.DiscardUnknown(m)
}

var xxx_messageInfo_GoModImport proto.InternalMessageInfo

func (m *GoModImport) GetPatterns() []string {
	if m != nil {
		return m.Patterns
	}
	return nil
}

func (m *GoModImport) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "anyvendor.Config")
	proto.RegisterType((*Import)(nil), "anyvendor.Import")
	proto.RegisterType((*Local)(nil), "anyvendor.Local")
	proto.RegisterType((*GoModImport)(nil), "anyvendor.GoModImport")
}

func init() { proto.RegisterFile("anyvendor.proto", fileDescriptor_2a8ec572c73c9b71) }

var fileDescriptor_2a8ec572c73c9b71 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xcc, 0xab, 0x2c,
	0x4b, 0xcd, 0x4b, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x48,
	0x89, 0x97, 0x25, 0xe6, 0x64, 0xa6, 0x24, 0x96, 0xa4, 0xea, 0xc3, 0x18, 0x10, 0x35, 0x4a, 0xb1,
	0x5c, 0x6c, 0xce, 0xf9, 0x79, 0x69, 0x99, 0xe9, 0x42, 0x6a, 0x5c, 0xac, 0x39, 0xf9, 0xc9, 0x89,
	0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x02, 0x7a, 0x08, 0xe3, 0x7c, 0x40, 0xe2, 0x41,
	0x10, 0x69, 0x21, 0x6d, 0x2e, 0xf6, 0xcc, 0xdc, 0x82, 0xfc, 0xa2, 0x92, 0x62, 0x09, 0x26, 0x05,
	0x66, 0x0d, 0x6e, 0x23, 0x41, 0x24, 0x95, 0x9e, 0x60, 0x99, 0x20, 0x98, 0x0a, 0x25, 0x3f, 0x2e,
	0x36, 0x88, 0x90, 0x90, 0x3e, 0x17, 0x5b, 0x7a, 0x7e, 0x7c, 0x6e, 0x7e, 0x8a, 0x04, 0x13, 0xd8,
	0x7c, 0x31, 0x24, 0x5d, 0xee, 0xf9, 0xbe, 0xf9, 0x29, 0x10, 0x75, 0x1e, 0x0c, 0x41, 0xac, 0xe9,
	0x20, 0xae, 0x93, 0x30, 0x17, 0x17, 0x44, 0x28, 0xa4, 0xb2, 0x20, 0x55, 0x88, 0x75, 0xc7, 0xcb,
	0x03, 0xcc, 0x8c, 0x4a, 0xfa, 0x5c, 0xac, 0x60, 0xc7, 0x08, 0xa9, 0x71, 0x71, 0x14, 0x24, 0x96,
	0x94, 0xa4, 0x16, 0xe5, 0x15, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x3a, 0x71, 0xed, 0x7a, 0x79,
	0x80, 0x99, 0x75, 0x12, 0x23, 0x13, 0x07, 0x63, 0x10, 0x5c, 0x4e, 0x29, 0x8a, 0x8b, 0x1b, 0xc9,
	0x74, 0x62, 0xb5, 0x09, 0x29, 0x73, 0xb1, 0x17, 0x24, 0x26, 0x67, 0x27, 0xa6, 0xa7, 0x82, 0x9d,
	0xcb, 0xe9, 0xc4, 0x09, 0x52, 0xc6, 0x52, 0xc4, 0x24, 0xc0, 0x18, 0x04, 0x93, 0x71, 0xd2, 0x88,
	0x52, 0x4b, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x2f, 0xce, 0xcf, 0xc9,
	0xd7, 0xcd, 0xcc, 0xd7, 0x87, 0x7b, 0x0b, 0xc1, 0x4a, 0x62, 0x03, 0x07, 0xb6, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xff, 0x41, 0x40, 0xfa, 0xa3, 0x01, 0x00, 0x00,
}
