name: pull_request

on:
  push:
    branches:
      - 'master'
  pull_request: { }

jobs:
  check-code-gen:
    name: check-code-gen
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Set up Go 
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          
      - name: Install Protoc
        #  this will need to change to v2 when we move to protoc >= 3.20
        #  protoc version will need to change to minor.patch too
        #  see https://github.com/arduino/setup-protoc/pull/78
        uses: arduino/setup-protoc@v1
        with:
          version: '3.15.8'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check code gen
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          ./ci/check-code-gen.sh

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Install Protoc
        #  this will need to change to v2 when we move to protoc >= 3.20
        #  protoc version will need to change to minor.patch too
        #  see https://github.com/arduino/setup-protoc/pull/78
        uses: arduino/setup-protoc@v1 
        with:
          version: '3.15.8'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unit Tests
        run: |
          make update-deps run-tests
