name: pull_request

on:
  push:
    branches:
      - 'master'
  pull_request: { }

jobs:
  check-code-gen:
    name: check-code-gen
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Set up Go 1.18
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: '3.15.8'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check code gen
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          ./ci/check-code-gen.sh

  unit-tests:
    name: unit-tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --prune --unshallow
      - name: Set up Go 1.18
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: '3.15.8'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Unit Tests
        run: |
          make update-deps run-tests
